export const eventData = {
  id: "freshmen-night",
  title: "Freshmen night",
  date: "3 สิงหาคม 2568",
  time: "16:00 - 20:00 น.",
  location: "สนามกีฬาจุฬาลงกรณ์มหาวิทยาลัย",
  description:
    "กิจกรรมต้อนรับนิสิตใหม่ CU รุ่น 109 สู่รั้วมหาวิทยาลัย และกระชับสัมพันธ์ อันดีระหว่างน้องใหม่คณะต่าง ๆ ภายในงานมีการจัดแสดงดนตรีโดยวงดนตรี เช่น Landokmai, Dept, Polycat, Tilly Birds การแสดงพิเศษจาก CUDC และละครนิเทศ จุฬาฯ",
  totalAttendees: 1096,
  studentCount: 1090,
  staffCount: 6,
};

export const FilterFacultyOptions = [
  { id: "f-0", label: "ทุกคณะ/หน่วยงาน" },
  { id: "f-1", label: "คณะวิศวกรรมศาสตร์" },
  { id: "f-2", label: "คณะอักษรศาสตร์" },
  { id: "f-3", label: "คณะวิทยาศาสตร์" },
  { id: "f-4", label: "คณะสถาปัตยกรรมศาสตร์" },
  { id: "f-5", label: "คณะพาณิชยศาสตร์และการบัญชี" },
  { id: "f-6", label: "คณะครุศาสตร์" },
  { id: "f-7", label: "คณะนิเทศศาสตร์" },
  { id: "f-8", label: "คณะเศรษฐศาสตร์" },
  { id: "f-9", label: "คณะนิติศาสตร์" },
  { id: "f-10", label: "คณะสัตวแพทยศาสตร์" },
  { id: "f-11", label: "คณะเภสัชศาสตร์" },
  { id: "f-12", label: "คณะทันตแพทยศาสตร์" },
  { id: "f-13", label: "คณะพยาบาลศาสตร์" },
  { id: "f-14", label: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์" },
];

export const FilterTimeOptions = [
  { id: "t-0", label: "ทุกช่วงเวลา" },
  { id: "t-1", label: "00:00 - 01:00 น." },
  { id: "t-2", label: "01:00 - 02:00 น." },
  { id: "t-3", label: "02:00 - 03:00 น." },
  { id: "t-4", label: "03:00 - 04:00 น." },
  { id: "t-5", label: "04:00 - 05:00 น." },
  { id: "t-6", label: "05:00 - 06:00 น." },
  { id: "t-7", label: "06:00 - 07:00 น." },
  { id: "t-8", label: "07:00 - 08:00 น." },
  { id: "t-9", label: "08:00 - 09:00 น." },
  { id: "t-10", label: "09:00 - 10:00 น." },
  { id: "t-11", label: "10:00 - 11:00 น." },
  { id: "t-12", label: "11:00 - 12:00 น." },
  { id: "t-13", label: "12:00 - 13:00 น." },
  { id: "t-14", label: "13:00 - 14:00 น." },
  { id: "t-15", label: "14:00 - 15:00 น." },
  { id: "t-16", label: "15:00 - 16:00 น." },
  { id: "t-17", label: "16:00 - 17:00 น." },
  { id: "t-18", label: "17:00 - 18:00 น." },
  { id: "t-19", label: "18:00 - 19:00 น." },
  { id: "t-20", label: "19:00 - 20:00 น." },
  { id: "t-21", label: "20:00 - 21:00 น." },
  { id: "t-22", label: "21:00 - 22:00 น." },
  { id: "t-23", label: "22:00 - 23:00 น." },
  { id: "t-24", label: "23:00 - 00:00 น." },
];


export const chartDataForComparePage = [
  {
    faculty: "คณะวิศวกรรมศาสตร์",
    data: [
      { time: "16:00 - 17:00", total: 225 },
      { time: "17:00 - 18:00", total: 198 },
      { time: "18:00 - 19:00", total: 165 },
      { time: "19:00 - 20:00", total: 142 },
      { time: "20:00 - 21:00", total: 98 },
    ],
  },
  {
    faculty: "คณะอักษรศาสตร์",
    data: [
      { time: "16:00 - 17:00", total: 121 },
      { time: "17:00 - 18:00", total: 405 },
      { time: "18:00 - 19:00", total: 282 },
      { time: "19:00 - 20:00", total: 117 },
      { time: "20:00 - 21:00", total: 90 },
    ],
  },
  {
    faculty: "คณะสถาปัตยกรรมศาสตร์",
    data: [
      { time: "16:00 - 17:00", total: 10 },
      { time: "17:00 - 18:00", total: 175 },
      { time: "18:00 - 19:00", total: 156 },
      { time: "19:00 - 20:00", total: 242 },
      { time: "20:00 - 21:00", total: 158 },
    ],
  },
  {
    faculty: "คณะวิทยาศาสตร์",
    data: [
      { time: "16:00 - 17:00", total: 188 },
      { time: "17:00 - 18:00", total: 165 },
      { time: "18:00 - 19:00", total: 106 },
      { time: "19:00 - 20:00", total: 140 },
      { time: "20:00 - 21:00", total: 210 },
    ],
  },
  {
    faculty: "คณะบริหารธุรกิจ",
    data: [
      { time: "16:00 - 17:00", total: 90 },
      { time: "17:00 - 18:00", total: 160 },
      { time: "18:00 - 19:00", total: 140 },
      { time: "19:00 - 20:00", total: 210 },
      { time: "20:00 - 21:00", total: 158 },
    ],
  },
];

// Deep Insight Faculty Data with Full data
export const deepInsightFacultyData = [
  {
    facultyId: "f-1",
    faculty: "คณะวิศวกรรมศาสตร์",
    data: [
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 225,
        staff: 0,
        total: 225,
        registered: 180,
        unregistered: 45,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 198,
        staff: 0,
        total: 198,
        registered: 158,
        unregistered: 40,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 165,
        staff: 0,
        total: 165,
        registered: 132,
        unregistered: 33,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 142,
        staff: 0,
        total: 142,
        registered: 114,
        unregistered: 28,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 98,
        staff: 0,
        total: 98,
        registered: 78,
        unregistered: 20,
      },
    ],
  },
  {
    facultyId: "f-2",
    faculty: "คณะอักษรศาสตร์",
    data: [
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 97,
        staff: 24,
        total: 121,
        registered: 107,
        unregistered: 14,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 324,
        staff: 81,
        total: 405,
        registered: 356,
        unregistered: 49,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 226,
        staff: 56,
        total: 282,
        registered: 248,
        unregistered: 34,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 94,
        staff: 23,
        total: 117,
        registered: 103,
        unregistered: 14,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 72,
        staff: 18,
        total: 90,
        registered: 79,
        unregistered: 11,
      },
    ],
  },
  {
    facultyId: "f-3",
    faculty: "คณะวิทยาศาสตร์",
    data: [
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 150,
        staff: 38,
        total: 188,
        registered: 150,
        unregistered: 38,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 132,
        staff: 33,
        total: 165,
        registered: 132,
        unregistered: 33,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 85,
        staff: 21,
        total: 106,
        registered: 85,
        unregistered: 21,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 112,
        staff: 28,
        total: 140,
        registered: 112,
        unregistered: 28,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 168,
        staff: 42,
        total: 210,
        registered: 168,
        unregistered: 42,
      },
    ],
  },
  {
    facultyId: "f-4",
    faculty: "คณะสถาปัตยกรรมศาสตร์",
    data: [
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 7,
        staff: 3,
        total: 10,
        registered: 7,
        unregistered: 3,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 140,
        staff: 35,
        total: 175,
        registered: 140,
        unregistered: 35,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 125,
        staff: 31,
        total: 156,
        registered: 125,
        unregistered: 31,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 194,
        staff: 48,
        total: 242,
        registered: 194,
        unregistered: 48,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 126,
        staff: 32,
        total: 158,
        registered: 126,
        unregistered: 32,
      },
    ],
  },
  {
    facultyId: "f-5",
    faculty: "คณะพาณิชยศาสตร์และการบัญชี",
    data: [
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 72,
        staff: 18,
        total: 90,
        registered: 72,
        unregistered: 18,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 128,
        staff: 32,
        total: 160,
        registered: 128,
        unregistered: 32,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 112,
        staff: 28,
        total: 140,
        registered: 112,
        unregistered: 28,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 168,
        staff: 42,
        total: 210,
        registered: 168,
        unregistered: 42,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 126,
        staff: 32,
        total: 158,
        registered: 126,
        unregistered: 32,
      },
    ],
  },
  {
    facultyId: "f-6",
    faculty: "คณะครุศาสตร์",
    data: [
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 68,
        staff: 7,
        total: 75,
        registered: 62,
        unregistered: 13,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 95,
        staff: 8,
        total: 103,
        registered: 88,
        unregistered: 15,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 82,
        staff: 6,
        total: 88,
        registered: 75,
        unregistered: 13,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 58,
        staff: 4,
        total: 62,
        registered: 54,
        unregistered: 8,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 42,
        staff: 3,
        total: 45,
        registered: 39,
        unregistered: 6,
      },
    ],
  },
  {
    facultyId: "f-7",
    faculty: "คณะนิเทศศาสตร์",
    data: [
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 92,
        staff: 8,
        total: 100,
        registered: 80,
        unregistered: 20,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 118,
        staff: 10,
        total: 128,
        registered: 110,
        unregistered: 18,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 105,
        staff: 9,
        total: 114,
        registered: 98,
        unregistered: 16,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 78,
        staff: 6,
        total: 84,
        registered: 72,
        unregistered: 12,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 52,
        staff: 4,
        total: 56,
        registered: 48,
        unregistered: 8,
      },
    ],
  },
  {
    facultyId: "f-8",
    faculty: "คณะเศรษฐศาสตร์",
    data: [
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 115,
        staff: 10,
        total: 125,
        registered: 98,
        unregistered: 27,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 142,
        staff: 12,
        total: 154,
        registered: 130,
        unregistered: 24,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 125,
        staff: 10,
        total: 135,
        registered: 115,
        unregistered: 20,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 98,
        staff: 8,
        total: 106,
        registered: 92,
        unregistered: 14,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 68,
        staff: 6,
        total: 74,
        registered: 65,
        unregistered: 9,
      },
    ],
  },
  {
    facultyId: "f-9",
    faculty: "คณะนิติศาสตร์",
    data: [
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 88,
        staff: 7,
        total: 95,
        registered: 78,
        unregistered: 17,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 112,
        staff: 10,
        total: 122,
        registered: 105,
        unregistered: 17,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 98,
        staff: 8,
        total: 106,
        registered: 92,
        unregistered: 14,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 72,
        staff: 6,
        total: 78,
        registered: 68,
        unregistered: 10,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 55,
        staff: 4,
        total: 59,
        registered: 52,
        unregistered: 7,
      },
    ],
  },
  {
    facultyId: "f-10",
    faculty: "คณะสัตวแพทยศาสตร์",
    data: [
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 52,
        staff: 5,
        total: 57,
        registered: 45,
        unregistered: 12,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 68,
        staff: 6,
        total: 74,
        registered: 62,
        unregistered: 12,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 58,
        staff: 5,
        total: 63,
        registered: 54,
        unregistered: 9,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 42,
        staff: 4,
        total: 46,
        registered: 38,
        unregistered: 8,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 28,
        staff: 2,
        total: 30,
        registered: 26,
        unregistered: 4,
      },
    ],
  },
  {
    facultyId: "f-11",
    faculty: "คณะเภสัชศาสตร์",
    data: [
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 42,
        staff: 3,
        total: 45,
        registered: 37,
        unregistered: 8,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 55,
        staff: 4,
        total: 59,
        registered: 50,
        unregistered: 9,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 48,
        staff: 4,
        total: 52,
        registered: 44,
        unregistered: 8,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 35,
        staff: 3,
        total: 38,
        registered: 33,
        unregistered: 5,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 22,
        staff: 2,
        total: 24,
        registered: 21,
        unregistered: 3,
      },
    ],
  },
  {
    facultyId: "f-12",
    faculty: "คณะทันตแพทยศาสตร์",
    data: [
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 32,
        staff: 3,
        total: 35,
        registered: 28,
        unregistered: 7,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 42,
        staff: 4,
        total: 46,
        registered: 38,
        unregistered: 8,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 38,
        staff: 3,
        total: 41,
        registered: 35,
        unregistered: 6,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 28,
        staff: 2,
        total: 30,
        registered: 26,
        unregistered: 4,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 18,
        staff: 2,
        total: 20,
        registered: 17,
        unregistered: 3,
      },
    ],
  },
  {
    facultyId: "f-13",
    faculty: "คณะพยาบาลศาสตร์",
    data: [
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 45,
        staff: 4,
        total: 49,
        registered: 39,
        unregistered: 10,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 58,
        staff: 5,
        total: 63,
        registered: 53,
        unregistered: 10,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 52,
        staff: 4,
        total: 56,
        registered: 48,
        unregistered: 8,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 38,
        staff: 3,
        total: 41,
        registered: 35,
        unregistered: 6,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 25,
        staff: 2,
        total: 27,
        registered: 23,
        unregistered: 4,
      },
    ],
  },
  {
    facultyId: "f-14",
    faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
    data: [
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 62,
        staff: 5,
        total: 67,
        registered: 54,
        unregistered: 13,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 78,
        staff: 7,
        total: 85,
        registered: 72,
        unregistered: 13,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 68,
        staff: 6,
        total: 74,
        registered: 63,
        unregistered: 11,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 52,
        staff: 4,
        total: 56,
        registered: 48,
        unregistered: 8,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 35,
        staff: 3,
        total: 38,
        registered: 33,
        unregistered: 5,
      },
    ],
  },
];

// Deep Insight Time Data with Full Faculty data
export const deepInsightTimeData = [
  {
    timeId: "t-17",
    time: "16:00 - 17:00",
    data: [
      {
        facultyId: "f-1",
        faculty: "คณะวิศวกรรมศาสตร์",
        students: 225,
        staff: 0,
        total: 225,
        registered: 180,
        unregistered: 45,
      },
      {
        facultyId: "f-2",
        faculty: "คณะอักษรศาสตร์",
        students: 97,
        staff: 24,
        total: 121,
        registered: 107,
        unregistered: 14,
      },
      {
        facultyId: "f-3",
        faculty: "คณะวิทยาศาสตร์",
        students: 150,
        staff: 38,
        total: 188,
        registered: 150,
        unregistered: 38,
      },
      {
        facultyId: "f-4",
        faculty: "คณะสถาปัตยกรรมศาสตร์",
        students: 7,
        staff: 3,
        total: 10,
        registered: 7,
        unregistered: 3,
      },
      {
        facultyId: "f-5",
        faculty: "คณะพาณิชยศาสตร์และการบัญชี",
        students: 72,
        staff: 18,
        total: 90,
        registered: 72,
        unregistered: 18,
      },
      {
        facultyId: "f-6",
        faculty: "คณะครุศาสตร์",
        students: 68,
        staff: 7,
        total: 75,
        registered: 62,
        unregistered: 13,
      },
      {
        facultyId: "f-7",
        faculty: "คณะนิเทศศาสตร์",
        students: 92,
        staff: 8,
        total: 100,
        registered: 80,
        unregistered: 20,
      },
      {
        facultyId: "f-8",
        faculty: "คณะเศรษฐศาสตร์",
        students: 115,
        staff: 10,
        total: 125,
        registered: 98,
        unregistered: 27,
      },
      {
        facultyId: "f-9",
        faculty: "คณะนิติศาสตร์",
        students: 88,
        staff: 7,
        total: 95,
        registered: 78,
        unregistered: 17,
      },
      {
        facultyId: "f-10",
        faculty: "คณะสัตวแพทยศาสตร์",
        students: 52,
        staff: 5,
        total: 57,
        registered: 45,
        unregistered: 12,
      },
      {
        facultyId: "f-11",
        faculty: "คณะเภสัชศาสตร์",
        students: 42,
        staff: 3,
        total: 45,
        registered: 37,
        unregistered: 8,
      },
      {
        facultyId: "f-12",
        faculty: "คณะทันตแพทยศาสตร์",
        students: 32,
        staff: 3,
        total: 35,
        registered: 28,
        unregistered: 7,
      },
      {
        facultyId: "f-13",
        faculty: "คณะพยาบาลศาสตร์",
        students: 45,
        staff: 4,
        total: 49,
        registered: 39,
        unregistered: 10,
      },
      {
        facultyId: "f-14",
        faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
        students: 62,
        staff: 5,
        total: 67,
        registered: 54,
        unregistered: 13,
      },
    ],
  },
  {
    timeId: "t-18",
    time: "17:00 - 18:00",
    data: [
      {
        facultyId: "f-1",
        faculty: "คณะวิศวกรรมศาสตร์",
        students: 198,
        staff: 0,
        total: 198,
        registered: 158,
        unregistered: 40,
      },
      {
        facultyId: "f-2",
        faculty: "คณะอักษรศาสตร์",
        students: 324,
        staff: 81,
        total: 405,
        registered: 356,
        unregistered: 49,
      },
      {
        facultyId: "f-3",
        faculty: "คณะวิทยาศาสตร์",
        students: 132,
        staff: 33,
        total: 165,
        registered: 132,
        unregistered: 33,
      },
      {
        facultyId: "f-4",
        faculty: "คณะสถาปัตยกรรมศาสตร์",
        students: 140,
        staff: 35,
        total: 175,
        registered: 140,
        unregistered: 35,
      },
      {
        facultyId: "f-5",
        faculty: "คณะพาณิชยศาสตร์และการบัญชี",
        students: 128,
        staff: 32,
        total: 160,
        registered: 128,
        unregistered: 32,
      },
      {
        facultyId: "f-6",
        faculty: "คณะครุศาสตร์",
        students: 95,
        staff: 8,
        total: 103,
        registered: 88,
        unregistered: 15,
      },
      {
        facultyId: "f-7",
        faculty: "คณะนิเทศศาสตร์",
        students: 118,
        staff: 10,
        total: 128,
        registered: 110,
        unregistered: 18,
      },
      {
        facultyId: "f-8",
        faculty: "คณะเศรษฐศาสตร์",
        students: 142,
        staff: 12,
        total: 154,
        registered: 130,
        unregistered: 24,
      },
      {
        facultyId: "f-9",
        faculty: "คณะนิติศาสตร์",
        students: 112,
        staff: 10,
        total: 122,
        registered: 105,
        unregistered: 17,
      },
      {
        facultyId: "f-10",
        faculty: "คณะสัตวแพทยศาสตร์",
        students: 68,
        staff: 6,
        total: 74,
        registered: 62,
        unregistered: 12,
      },
      {
        facultyId: "f-11",
        faculty: "คณะเภสัชศาสตร์",
        students: 55,
        staff: 4,
        total: 59,
        registered: 50,
        unregistered: 9,
      },
      {
        facultyId: "f-12",
        faculty: "คณะทันตแพทยศาสตร์",
        students: 42,
        staff: 4,
        total: 46,
        registered: 38,
        unregistered: 8,
      },
      {
        facultyId: "f-13",
        faculty: "คณะพยาบาลศาสตร์",
        students: 58,
        staff: 5,
        total: 63,
        registered: 53,
        unregistered: 10,
      },
      {
        facultyId: "f-14",
        faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
        students: 78,
        staff: 7,
        total: 85,
        registered: 72,
        unregistered: 13,
      },
    ],
  },
  {
    timeId: "t-19",
    time: "18:00 - 19:00",
    data: [
      {
        facultyId: "f-1",
        faculty: "คณะวิศวกรรมศาสตร์",
        students: 165,
        staff: 0,
        total: 165,
        registered: 132,
        unregistered: 33,
      },
      {
        facultyId: "f-2",
        faculty: "คณะอักษรศาสตร์",
        students: 226,
        staff: 56,
        total: 282,
        registered: 248,
        unregistered: 34,
      },
      {
        facultyId: "f-3",
        faculty: "คณะวิทยาศาสตร์",
        students: 85,
        staff: 21,
        total: 106,
        registered: 85,
        unregistered: 21,
      },
      {
        facultyId: "f-4",
        faculty: "คณะสถาปัตยกรรมศาสตร์",
        students: 125,
        staff: 31,
        total: 156,
        registered: 125,
        unregistered: 31,
      },
      {
        facultyId: "f-5",
        faculty: "คณะพาณิชยศาสตร์และการบัญชี",
        students: 112,
        staff: 28,
        total: 140,
        registered: 112,
        unregistered: 28,
      },
      {
        facultyId: "f-6",
        faculty: "คณะครุศาสตร์",
        students: 82,
        staff: 6,
        total: 88,
        registered: 75,
        unregistered: 13,
      },
      {
        facultyId: "f-7",
        faculty: "คณะนิเทศศาสตร์",
        students: 105,
        staff: 9,
        total: 114,
        registered: 98,
        unregistered: 16,
      },
      {
        facultyId: "f-8",
        faculty: "คณะเศรษฐศาสตร์",
        students: 125,
        staff: 10,
        total: 135,
        registered: 115,
        unregistered: 20,
      },
      {
        facultyId: "f-9",
        faculty: "คณะนิติศาสตร์",
        students: 98,
        staff: 8,
        total: 106,
        registered: 92,
        unregistered: 14,
      },
      {
        facultyId: "f-10",
        faculty: "คณะสัตวแพทยศาสตร์",
        students: 58,
        staff: 5,
        total: 63,
        registered: 54,
        unregistered: 9,
      },
      {
        facultyId: "f-11",
        faculty: "คณะเภสัชศาสตร์",
        students: 48,
        staff: 4,
        total: 52,
        registered: 44,
        unregistered: 8,
      },
      {
        facultyId: "f-12",
        faculty: "คณะทันตแพทยศาสตร์",
        students: 38,
        staff: 3,
        total: 41,
        registered: 35,
        unregistered: 6,
      },
      {
        facultyId: "f-13",
        faculty: "คณะพยาบาลศาสตร์",
        students: 52,
        staff: 4,
        total: 56,
        registered: 48,
        unregistered: 8,
      },
      {
        facultyId: "f-14",
        faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
        students: 68,
        staff: 6,
        total: 74,
        registered: 63,
        unregistered: 11,
      },
    ],
  },
  {
    timeId: "t-20",
    time: "19:00 - 20:00",
    data: [
      {
        facultyId: "f-1",
        faculty: "คณะวิศวกรรมศาสตร์",
        students: 142,
        staff: 0,
        total: 142,
        registered: 114,
        unregistered: 28,
      },
      {
        facultyId: "f-2",
        faculty: "คณะอักษรศาสตร์",
        students: 94,
        staff: 23,
        total: 117,
        registered: 103,
        unregistered: 14,
      },
      {
        facultyId: "f-3",
        faculty: "คณะวิทยาศาสตร์",
        students: 112,
        staff: 28,
        total: 140,
        registered: 112,
        unregistered: 28,
      },
      {
        facultyId: "f-4",
        faculty: "คณะสถาปัตยกรรมศาสตร์",
        students: 194,
        staff: 48,
        total: 242,
        registered: 194,
        unregistered: 48,
      },
      {
        facultyId: "f-5",
        faculty: "คณะพาณิชยศาสตร์และการบัญชี",
        students: 168,
        staff: 42,
        total: 210,
        registered: 168,
        unregistered: 42,
      },
      {
        facultyId: "f-6",
        faculty: "คณะครุศาสตร์",
        students: 58,
        staff: 4,
        total: 62,
        registered: 54,
        unregistered: 8,
      },
      {
        facultyId: "f-7",
        faculty: "คณะนิเทศศาสตร์",
        students: 78,
        staff: 6,
        total: 84,
        registered: 72,
        unregistered: 12,
      },
      {
        facultyId: "f-8",
        faculty: "คณะเศรษฐศาสตร์",
        students: 98,
        staff: 8,
        total: 106,
        registered: 92,
        unregistered: 14,
      },
      {
        facultyId: "f-9",
        faculty: "คณะนิติศาสตร์",
        students: 72,
        staff: 6,
        total: 78,
        registered: 68,
        unregistered: 10,
      },
      {
        facultyId: "f-10",
        faculty: "คณะสัตวแพทยศาสตร์",
        students: 42,
        staff: 4,
        total: 46,
        registered: 38,
        unregistered: 8,
      },
      {
        facultyId: "f-11",
        faculty: "คณะเภสัชศาสตร์",
        students: 35,
        staff: 3,
        total: 38,
        registered: 33,
        unregistered: 5,
      },
      {
        facultyId: "f-12",
        faculty: "คณะทันตแพทยศาสตร์",
        students: 28,
        staff: 2,
        total: 30,
        registered: 26,
        unregistered: 4,
      },
      {
        facultyId: "f-13",
        faculty: "คณะพยาบาลศาสตร์",
        students: 38,
        staff: 3,
        total: 41,
        registered: 35,
        unregistered: 6,
      },
      {
        facultyId: "f-14",
        faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
        students: 52,
        staff: 4,
        total: 56,
        registered: 48,
        unregistered: 8,
      },
    ],
  },
  {
    timeId: "t-21",
    time: "20:00 - 21:00",
    data: [
      {
        facultyId: "f-1",
        faculty: "คณะวิศวกรรมศาสตร์",
        students: 98,
        staff: 0,
        total: 98,
        registered: 78,
        unregistered: 20,
      },
      {
        facultyId: "f-2",
        faculty: "คณะอักษรศาสตร์",
        students: 72,
        staff: 18,
        total: 90,
        registered: 79,
        unregistered: 11,
      },
      {
        facultyId: "f-3",
        faculty: "คณะวิทยาศาสตร์",
        students: 168,
        staff: 42,
        total: 210,
        registered: 168,
        unregistered: 42,
      },
      {
        facultyId: "f-4",
        faculty: "คณะสถาปัตยกรรมศาสตร์",
        students: 126,
        staff: 32,
        total: 158,
        registered: 126,
        unregistered: 32,
      },
      {
        facultyId: "f-5",
        faculty: "คณะพาณิชยศาสตร์และการบัญชี",
        students: 126,
        staff: 32,
        total: 158,
        registered: 126,
        unregistered: 32,
      },
      {
        facultyId: "f-6",
        faculty: "คณะครุศาสตร์",
        students: 42,
        staff: 3,
        total: 45,
        registered: 39,
        unregistered: 6,
      },
      {
        facultyId: "f-7",
        faculty: "คณะนิเทศศาสตร์",
        students: 52,
        staff: 4,
        total: 56,
        registered: 48,
        unregistered: 8,
      },
      {
        facultyId: "f-8",
        faculty: "คณะเศรษฐศาสตร์",
        students: 68,
        staff: 6,
        total: 74,
        registered: 65,
        unregistered: 9,
      },
      {
        facultyId: "f-9",
        faculty: "คณะนิติศาสตร์",
        students: 55,
        staff: 4,
        total: 59,
        registered: 52,
        unregistered: 7,
      },
      {
        facultyId: "f-10",
        faculty: "คณะสัตวแพทยศาสตร์",
        students: 28,
        staff: 2,
        total: 30,
        registered: 26,
        unregistered: 4,
      },
      {
        facultyId: "f-11",
        faculty: "คณะเภสัชศาสตร์",
        students: 22,
        staff: 2,
        total: 24,
        registered: 21,
        unregistered: 3,
      },
      {
        facultyId: "f-12",
        faculty: "คณะทันตแพทยศาสตร์",
        students: 18,
        staff: 2,
        total: 20,
        registered: 17,
        unregistered: 3,
      },
      {
        facultyId: "f-13",
        faculty: "คณะพยาบาลศาสตร์",
        students: 25,
        staff: 2,
        total: 27,
        registered: 23,
        unregistered: 4,
      },
      {
        facultyId: "f-14",
        faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
        students: 35,
        staff: 3,
        total: 38,
        registered: 33,
        unregistered: 5,
      },
    ],
  },
];
