export const eventData = {
  id: "freshmen-night",
  title: "Freshmen night",
  date: "3 สิงหาคม 2568",
  time: "16:00 - 20:00 น.",
  location: "สนามกีฬาจุฬาลงกรณ์มหาวิทยาลัย",
  description:
    "กิจกรรมต้อนรับนิสิตใหม่ CU รุ่น 109 สู่รั้วมหาวิทยาลัย และกระชับสัมพันธ์ อันดีระหว่างน้องใหม่คณะต่าง ๆ ภายในงานมีการจัดแสดงดนตรีโดยวงดนตรี เช่น Landokmai, Dept, Polycat, Tilly Birds การแสดงพิเศษจาก CUDC และละครนิเทศ จุฬาฯ",
  totalAttendees: 21240,
  studentCount: 1090,
  staffCount: 6,
};

export const FilterFacultyOptions = [
  { id: "f-0", label: "ทุกคณะ/หน่วยงาน" },
  { id: "f-1", label: "คณะวิศวกรรมศาสตร์" },
  { id: "f-2", label: "คณะอักษรศาสตร์" },
  { id: "f-3", label: "คณะวิทยาศาสตร์" },
  { id: "f-4", label: "คณะสถาปัตยกรรมศาสตร์" },
  { id: "f-5", label: "คณะพาณิชยศาสตร์และการบัญชี" },
  { id: "f-6", label: "คณะครุศาสตร์" },
  { id: "f-7", label: "คณะนิเทศศาสตร์" },
  { id: "f-8", label: "คณะเศรษฐศาสตร์" },
  { id: "f-9", label: "คณะนิติศาสตร์" },
  { id: "f-10", label: "คณะสัตวแพทยศาสตร์" },
  { id: "f-11", label: "คณะเภสัชศาสตร์" },
  { id: "f-12", label: "คณะทันตแพทยศาสตร์" },
  { id: "f-13", label: "คณะพยาบาลศาสตร์" },
  { id: "f-14", label: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์" },
];

export const FilterTimeOptions = [
  { id: "t-0", label: "ทุกช่วงเวลา" },
  { id: "t-1", label: "00:00 - 01:00 น." },
  { id: "t-2", label: "01:00 - 02:00 น." },
  { id: "t-3", label: "02:00 - 03:00 น." },
  { id: "t-4", label: "03:00 - 04:00 น." },
  { id: "t-5", label: "04:00 - 05:00 น." },
  { id: "t-6", label: "05:00 - 06:00 น." },
  { id: "t-7", label: "06:00 - 07:00 น." },
  { id: "t-8", label: "07:00 - 08:00 น." },
  { id: "t-9", label: "08:00 - 09:00 น." },
  { id: "t-10", label: "09:00 - 10:00 น." },
  { id: "t-11", label: "10:00 - 11:00 น." },
  { id: "t-12", label: "11:00 - 12:00 น." },
  { id: "t-13", label: "12:00 - 13:00 น." },
  { id: "t-14", label: "13:00 - 14:00 น." },
  { id: "t-15", label: "14:00 - 15:00 น." },
  { id: "t-16", label: "15:00 - 16:00 น." },
  { id: "t-17", label: "16:00 - 17:00 น." },
  { id: "t-18", label: "17:00 - 18:00 น." },
  { id: "t-19", label: "18:00 - 19:00 น." },
  { id: "t-20", label: "19:00 - 20:00 น." },
  { id: "t-21", label: "20:00 - 21:00 น." },
  { id: "t-22", label: "21:00 - 22:00 น." },
  { id: "t-23", label: "22:00 - 23:00 น." },
  { id: "t-24", label: "23:00 - 00:00 น." },
];

// Deep Insight Faculty Data with Full data
export const deepInsightFacultyData = [
  {
    facultyId: "f-1",
    faculty: "คณะวิศวกรรมศาสตร์",
    data: [
      {
        timeId: "t-9",
        time: "08:00 - 09:00",
        students: 120,
        staff: 30,
        total: 150,
        registered: 120,
        unregistered: 30,
      },
      {
        timeId: "t-10",
        time: "09:00 - 10:00",
        students: 160,
        staff: 40,
        total: 200,
        registered: 160,
        unregistered: 40,
      },
      {
        timeId: "t-11",
        time: "10:00 - 11:00",
        students: 180,
        staff: 45,
        total: 225,
        registered: 180,
        unregistered: 45,
      },
      {
        timeId: "t-12",
        time: "11:00 - 12:00",
        students: 200,
        staff: 50,
        total: 250,
        registered: 200,
        unregistered: 50,
      },
      {
        timeId: "t-13",
        time: "12:00 - 13:00",
        students: 160,
        staff: 40,
        total: 200,
        registered: 160,
        unregistered: 40,
      },
      {
        timeId: "t-14",
        time: "13:00 - 14:00",
        students: 180,
        staff: 45,
        total: 225,
        registered: 180,
        unregistered: 45,
      },
      {
        timeId: "t-15",
        time: "14:00 - 15:00",
        students: 220,
        staff: 55,
        total: 275,
        registered: 220,
        unregistered: 55,
      },
      {
        timeId: "t-16",
        time: "15:00 - 16:00",
        students: 240,
        staff: 60,
        total: 300,
        registered: 240,
        unregistered: 60,
      },
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 280,
        staff: 70,
        total: 350,
        registered: 280,
        unregistered: 70,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 340,
        staff: 85,
        total: 425,
        registered: 340,
        unregistered: 85,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 240,
        staff: 60,
        total: 300,
        registered: 240,
        unregistered: 60,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 160,
        staff: 40,
        total: 200,
        registered: 160,
        unregistered: 40,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 80,
        staff: 20,
        total: 100,
        registered: 80,
        unregistered: 20,
      },
    ],
  },
  {
    facultyId: "f-2",
    faculty: "คณะอักษรศาสตร์",
    data: [
      {
        timeId: "t-9",
        time: "08:00 - 09:00",
        students: 80,
        staff: 20,
        total: 100,
        registered: 80,
        unregistered: 20,
      },
      {
        timeId: "t-10",
        time: "09:00 - 10:00",
        students: 100,
        staff: 25,
        total: 125,
        registered: 100,
        unregistered: 25,
      },
      {
        timeId: "t-11",
        time: "10:00 - 11:00",
        students: 140,
        staff: 35,
        total: 175,
        registered: 140,
        unregistered: 35,
      },
      {
        timeId: "t-12",
        time: "11:00 - 12:00",
        students: 200,
        staff: 50,
        total: 250,
        registered: 200,
        unregistered: 50,
      },
      {
        timeId: "t-13",
        time: "12:00 - 13:00",
        students: 180,
        staff: 45,
        total: 225,
        registered: 180,
        unregistered: 45,
      },
      {
        timeId: "t-14",
        time: "13:00 - 14:00",
        students: 240,
        staff: 60,
        total: 300,
        registered: 240,
        unregistered: 60,
      },
      {
        timeId: "t-15",
        time: "14:00 - 15:00",
        students: 320,
        staff: 80,
        total: 400,
        registered: 320,
        unregistered: 80,
      },
      {
        timeId: "t-16",
        time: "15:00 - 16:00",
        students: 360,
        staff: 90,
        total: 450,
        registered: 360,
        unregistered: 90,
      },
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 120,
        staff: 30,
        total: 150,
        registered: 120,
        unregistered: 30,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 480,
        staff: 120,
        total: 600,
        registered: 480,
        unregistered: 120,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 400,
        staff: 100,
        total: 500,
        registered: 400,
        unregistered: 100,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 200,
        staff: 50,
        total: 250,
        registered: 200,
        unregistered: 50,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 100,
        staff: 25,
        total: 125,
        registered: 100,
        unregistered: 25,
      },
    ],
  },
  {
    facultyId: "f-3",
    faculty: "คณะวิทยาศาสตร์",
    data: [
      {
        timeId: "t-9",
        time: "08:00 - 09:00",
        students: 100,
        staff: 25,
        total: 125,
        registered: 100,
        unregistered: 25,
      },
      {
        timeId: "t-10",
        time: "09:00 - 10:00",
        students: 140,
        staff: 35,
        total: 175,
        registered: 140,
        unregistered: 35,
      },
      {
        timeId: "t-11",
        time: "10:00 - 11:00",
        students: 180,
        staff: 45,
        total: 225,
        registered: 180,
        unregistered: 45,
      },
      {
        timeId: "t-12",
        time: "11:00 - 12:00",
        students: 220,
        staff: 55,
        total: 275,
        registered: 220,
        unregistered: 55,
      },
      {
        timeId: "t-13",
        time: "12:00 - 13:00",
        students: 160,
        staff: 40,
        total: 200,
        registered: 160,
        unregistered: 40,
      },
      {
        timeId: "t-14",
        time: "13:00 - 14:00",
        students: 200,
        staff: 50,
        total: 250,
        registered: 200,
        unregistered: 50,
      },
      {
        timeId: "t-15",
        time: "14:00 - 15:00",
        students: 240,
        staff: 60,
        total: 300,
        registered: 240,
        unregistered: 60,
      },
      {
        timeId: "t-16",
        time: "15:00 - 16:00",
        students: 280,
        staff: 70,
        total: 350,
        registered: 280,
        unregistered: 70,
      },
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 160,
        staff: 40,
        total: 200,
        registered: 160,
        unregistered: 40,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 240,
        staff: 60,
        total: 300,
        registered: 240,
        unregistered: 60,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 320,
        staff: 80,
        total: 400,
        registered: 320,
        unregistered: 80,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 280,
        staff: 70,
        total: 350,
        registered: 280,
        unregistered: 70,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 200,
        staff: 50,
        total: 250,
        registered: 200,
        unregistered: 50,
      },
    ],
  },
  {
    facultyId: "f-4",
    faculty: "คณะสถาปัตยกรรมศาสตร์",
    data: [
      {
        timeId: "t-9",
        time: "08:00 - 09:00",
        students: 60,
        staff: 15,
        total: 75,
        registered: 60,
        unregistered: 15,
      },
      {
        timeId: "t-10",
        time: "09:00 - 10:00",
        students: 80,
        staff: 20,
        total: 100,
        registered: 80,
        unregistered: 20,
      },
      {
        timeId: "t-11",
        time: "10:00 - 11:00",
        students: 100,
        staff: 25,
        total: 125,
        registered: 100,
        unregistered: 25,
      },
      {
        timeId: "t-12",
        time: "11:00 - 12:00",
        students: 120,
        staff: 30,
        total: 150,
        registered: 120,
        unregistered: 30,
      },
      {
        timeId: "t-13",
        time: "12:00 - 13:00",
        students: 100,
        staff: 25,
        total: 125,
        registered: 100,
        unregistered: 25,
      },
      {
        timeId: "t-14",
        time: "13:00 - 14:00",
        students: 140,
        staff: 35,
        total: 175,
        registered: 140,
        unregistered: 35,
      },
      {
        timeId: "t-15",
        time: "14:00 - 15:00",
        students: 180,
        staff: 45,
        total: 225,
        registered: 180,
        unregistered: 45,
      },
      {
        timeId: "t-16",
        time: "15:00 - 16:00",
        students: 220,
        staff: 55,
        total: 275,
        registered: 220,
        unregistered: 55,
      },
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 40,
        staff: 10,
        total: 50,
        registered: 40,
        unregistered: 10,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 120,
        staff: 30,
        total: 150,
        registered: 120,
        unregistered: 30,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 200,
        staff: 50,
        total: 250,
        registered: 200,
        unregistered: 50,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 280,
        staff: 70,
        total: 350,
        registered: 280,
        unregistered: 70,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 240,
        staff: 60,
        total: 300,
        registered: 240,
        unregistered: 60,
      },
    ],
  },
  {
    facultyId: "f-5",
    faculty: "คณะพาณิชยศาสตร์และการบัญชี",
    data: [
      {
        timeId: "t-9",
        time: "08:00 - 09:00",
        students: 120,
        staff: 30,
        total: 150,
        registered: 120,
        unregistered: 30,
      },
      {
        timeId: "t-10",
        time: "09:00 - 10:00",
        students: 140,
        staff: 35,
        total: 175,
        registered: 140,
        unregistered: 35,
      },
      {
        timeId: "t-11",
        time: "10:00 - 11:00",
        students: 160,
        staff: 40,
        total: 200,
        registered: 160,
        unregistered: 40,
      },
      {
        timeId: "t-12",
        time: "11:00 - 12:00",
        students: 180,
        staff: 45,
        total: 225,
        registered: 180,
        unregistered: 45,
      },
      {
        timeId: "t-13",
        time: "12:00 - 13:00",
        students: 140,
        staff: 35,
        total: 175,
        registered: 140,
        unregistered: 35,
      },
      {
        timeId: "t-14",
        time: "13:00 - 14:00",
        students: 160,
        staff: 40,
        total: 200,
        registered: 160,
        unregistered: 40,
      },
      {
        timeId: "t-15",
        time: "14:00 - 15:00",
        students: 200,
        staff: 50,
        total: 250,
        registered: 200,
        unregistered: 50,
      },
      {
        timeId: "t-16",
        time: "15:00 - 16:00",
        students: 240,
        staff: 60,
        total: 300,
        registered: 240,
        unregistered: 60,
      },
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 180,
        staff: 45,
        total: 225,
        registered: 180,
        unregistered: 45,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 220,
        staff: 55,
        total: 275,
        registered: 220,
        unregistered: 55,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 260,
        staff: 65,
        total: 325,
        registered: 260,
        unregistered: 65,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 240,
        staff: 60,
        total: 300,
        registered: 240,
        unregistered: 60,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 200,
        staff: 50,
        total: 250,
        registered: 200,
        unregistered: 50,
      },
    ],
  },
  {
    facultyId: "f-6",
    faculty: "คณะครุศาสตร์",
    data: [
      {
        timeId: "t-9",
        time: "08:00 - 09:00",
        students: 68,
        staff: 7,
        total: 75,
        registered: 62,
        unregistered: 13,
      },
      {
        timeId: "t-10",
        time: "09:00 - 10:00",
        students: 75,
        staff: 8,
        total: 83,
        registered: 68,
        unregistered: 15,
      },
      {
        timeId: "t-11",
        time: "10:00 - 11:00",
        students: 82,
        staff: 9,
        total: 91,
        registered: 75,
        unregistered: 16,
      },
      {
        timeId: "t-12",
        time: "11:00 - 12:00",
        students: 88,
        staff: 9,
        total: 97,
        registered: 80,
        unregistered: 17,
      },
      {
        timeId: "t-13",
        time: "12:00 - 13:00",
        students: 78,
        staff: 8,
        total: 86,
        registered: 72,
        unregistered: 14,
      },
      {
        timeId: "t-14",
        time: "13:00 - 14:00",
        students: 85,
        staff: 8,
        total: 93,
        registered: 78,
        unregistered: 15,
      },
      {
        timeId: "t-15",
        time: "14:00 - 15:00",
        students: 92,
        staff: 9,
        total: 101,
        registered: 84,
        unregistered: 17,
      },
      {
        timeId: "t-16",
        time: "15:00 - 16:00",
        students: 98,
        staff: 10,
        total: 108,
        registered: 90,
        unregistered: 18,
      },
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 68,
        staff: 7,
        total: 75,
        registered: 62,
        unregistered: 13,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 95,
        staff: 8,
        total: 103,
        registered: 88,
        unregistered: 15,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 82,
        staff: 6,
        total: 88,
        registered: 75,
        unregistered: 13,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 58,
        staff: 4,
        total: 62,
        registered: 54,
        unregistered: 8,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 42,
        staff: 3,
        total: 45,
        registered: 39,
        unregistered: 6,
      },
    ],
  },
  {
    facultyId: "f-7",
    faculty: "คณะนิเทศศาสตร์",
    data: [
      {
        timeId: "t-9",
        time: "08:00 - 09:00",
        students: 92,
        staff: 8,
        total: 100,
        registered: 80,
        unregistered: 20,
      },
      {
        timeId: "t-10",
        time: "09:00 - 10:00",
        students: 95,
        staff: 9,
        total: 104,
        registered: 85,
        unregistered: 19,
      },
      {
        timeId: "t-11",
        time: "10:00 - 11:00",
        students: 105,
        staff: 10,
        total: 115,
        registered: 92,
        unregistered: 23,
      },
      {
        timeId: "t-12",
        time: "11:00 - 12:00",
        students: 112,
        staff: 10,
        total: 122,
        registered: 98,
        unregistered: 24,
      },
      {
        timeId: "t-13",
        time: "12:00 - 13:00",
        students: 98,
        staff: 9,
        total: 107,
        registered: 88,
        unregistered: 19,
      },
      {
        timeId: "t-14",
        time: "13:00 - 14:00",
        students: 108,
        staff: 10,
        total: 118,
        registered: 95,
        unregistered: 23,
      },
      {
        timeId: "t-15",
        time: "14:00 - 15:00",
        students: 115,
        staff: 10,
        total: 125,
        registered: 102,
        unregistered: 23,
      },
      {
        timeId: "t-16",
        time: "15:00 - 16:00",
        students: 122,
        staff: 11,
        total: 133,
        registered: 108,
        unregistered: 25,
      },
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 92,
        staff: 8,
        total: 100,
        registered: 80,
        unregistered: 20,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 118,
        staff: 10,
        total: 128,
        registered: 110,
        unregistered: 18,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 105,
        staff: 9,
        total: 114,
        registered: 98,
        unregistered: 16,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 78,
        staff: 6,
        total: 84,
        registered: 72,
        unregistered: 12,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 52,
        staff: 4,
        total: 56,
        registered: 48,
        unregistered: 8,
      },
    ],
  },
  {
    facultyId: "f-8",
    faculty: "คณะเศรษฐศาสตร์",
    data: [
      {
        timeId: "t-9",
        time: "08:00 - 09:00",
        students: 115,
        staff: 10,
        total: 125,
        registered: 98,
        unregistered: 27,
      },
      {
        timeId: "t-10",
        time: "09:00 - 10:00",
        students: 120,
        staff: 11,
        total: 131,
        registered: 105,
        unregistered: 26,
      },
      {
        timeId: "t-11",
        time: "10:00 - 11:00",
        students: 130,
        staff: 12,
        total: 142,
        registered: 115,
        unregistered: 27,
      },
      {
        timeId: "t-12",
        time: "11:00 - 12:00",
        students: 138,
        staff: 12,
        total: 150,
        registered: 122,
        unregistered: 28,
      },
      {
        timeId: "t-13",
        time: "12:00 - 13:00",
        students: 122,
        staff: 11,
        total: 133,
        registered: 110,
        unregistered: 23,
      },
      {
        timeId: "t-14",
        time: "13:00 - 14:00",
        students: 132,
        staff: 12,
        total: 144,
        registered: 118,
        unregistered: 26,
      },
      {
        timeId: "t-15",
        time: "14:00 - 15:00",
        students: 140,
        staff: 12,
        total: 152,
        registered: 125,
        unregistered: 27,
      },
      {
        timeId: "t-16",
        time: "15:00 - 16:00",
        students: 148,
        staff: 13,
        total: 161,
        registered: 132,
        unregistered: 29,
      },
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 115,
        staff: 10,
        total: 125,
        registered: 98,
        unregistered: 27,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 142,
        staff: 12,
        total: 154,
        registered: 130,
        unregistered: 24,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 125,
        staff: 10,
        total: 135,
        registered: 115,
        unregistered: 20,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 98,
        staff: 8,
        total: 106,
        registered: 92,
        unregistered: 14,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 68,
        staff: 6,
        total: 74,
        registered: 65,
        unregistered: 9,
      },
    ],
  },
  {
    facultyId: "f-9",
    faculty: "คณะนิติศาสตร์",
    data: [
      {
        timeId: "t-9",
        time: "08:00 - 09:00",
        students: 88,
        staff: 7,
        total: 95,
        registered: 78,
        unregistered: 17,
      },
      {
        timeId: "t-10",
        time: "09:00 - 10:00",
        students: 95,
        staff: 8,
        total: 103,
        registered: 85,
        unregistered: 18,
      },
      {
        timeId: "t-11",
        time: "10:00 - 11:00",
        students: 102,
        staff: 9,
        total: 111,
        registered: 92,
        unregistered: 19,
      },
      {
        timeId: "t-12",
        time: "11:00 - 12:00",
        students: 108,
        staff: 9,
        total: 117,
        registered: 98,
        unregistered: 19,
      },
      {
        timeId: "t-13",
        time: "12:00 - 13:00",
        students: 95,
        staff: 8,
        total: 103,
        registered: 86,
        unregistered: 17,
      },
      {
        timeId: "t-14",
        time: "13:00 - 14:00",
        students: 102,
        staff: 9,
        total: 111,
        registered: 92,
        unregistered: 19,
      },
      {
        timeId: "t-15",
        time: "14:00 - 15:00",
        students: 108,
        staff: 9,
        total: 117,
        registered: 98,
        unregistered: 19,
      },
      {
        timeId: "t-16",
        time: "15:00 - 16:00",
        students: 115,
        staff: 10,
        total: 125,
        registered: 104,
        unregistered: 21,
      },
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 88,
        staff: 7,
        total: 95,
        registered: 78,
        unregistered: 17,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 112,
        staff: 10,
        total: 122,
        registered: 105,
        unregistered: 17,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 98,
        staff: 8,
        total: 106,
        registered: 92,
        unregistered: 14,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 72,
        staff: 6,
        total: 78,
        registered: 68,
        unregistered: 10,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 55,
        staff: 4,
        total: 59,
        registered: 52,
        unregistered: 7,
      },
    ],
  },
  {
    facultyId: "f-10",
    faculty: "คณะสัตวแพทยศาสตร์",
    data: [
      {
        timeId: "t-9",
        time: "08:00 - 09:00",
        students: 52,
        staff: 5,
        total: 57,
        registered: 45,
        unregistered: 12,
      },
      {
        timeId: "t-10",
        time: "09:00 - 10:00",
        students: 58,
        staff: 5,
        total: 63,
        registered: 50,
        unregistered: 13,
      },
      {
        timeId: "t-11",
        time: "10:00 - 11:00",
        students: 62,
        staff: 6,
        total: 68,
        registered: 55,
        unregistered: 13,
      },
      {
        timeId: "t-12",
        time: "11:00 - 12:00",
        students: 68,
        staff: 6,
        total: 74,
        registered: 60,
        unregistered: 14,
      },
      {
        timeId: "t-13",
        time: "12:00 - 13:00",
        students: 58,
        staff: 5,
        total: 63,
        registered: 52,
        unregistered: 11,
      },
      {
        timeId: "t-14",
        time: "13:00 - 14:00",
        students: 64,
        staff: 6,
        total: 70,
        registered: 57,
        unregistered: 13,
      },
      {
        timeId: "t-15",
        time: "14:00 - 15:00",
        students: 70,
        staff: 6,
        total: 76,
        registered: 62,
        unregistered: 14,
      },
      {
        timeId: "t-16",
        time: "15:00 - 16:00",
        students: 75,
        staff: 7,
        total: 82,
        registered: 67,
        unregistered: 15,
      },
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 52,
        staff: 5,
        total: 57,
        registered: 45,
        unregistered: 12,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 68,
        staff: 6,
        total: 74,
        registered: 62,
        unregistered: 12,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 58,
        staff: 5,
        total: 63,
        registered: 54,
        unregistered: 9,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 42,
        staff: 4,
        total: 46,
        registered: 38,
        unregistered: 8,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 28,
        staff: 2,
        total: 30,
        registered: 26,
        unregistered: 4,
      },
    ],
  },
  {
    facultyId: "f-11",
    faculty: "คณะเภสัชศาสตร์",
    data: [
      {
        timeId: "t-9",
        time: "08:00 - 09:00",
        students: 42,
        staff: 3,
        total: 45,
        registered: 37,
        unregistered: 8,
      },
      {
        timeId: "t-10",
        time: "09:00 - 10:00",
        students: 48,
        staff: 4,
        total: 52,
        registered: 42,
        unregistered: 10,
      },
      {
        timeId: "t-11",
        time: "10:00 - 11:00",
        students: 52,
        staff: 4,
        total: 56,
        registered: 46,
        unregistered: 10,
      },
      {
        timeId: "t-12",
        time: "11:00 - 12:00",
        students: 58,
        staff: 5,
        total: 63,
        registered: 52,
        unregistered: 11,
      },
      {
        timeId: "t-13",
        time: "12:00 - 13:00",
        students: 48,
        staff: 4,
        total: 52,
        registered: 43,
        unregistered: 9,
      },
      {
        timeId: "t-14",
        time: "13:00 - 14:00",
        students: 54,
        staff: 4,
        total: 58,
        registered: 48,
        unregistered: 10,
      },
      {
        timeId: "t-15",
        time: "14:00 - 15:00",
        students: 58,
        staff: 5,
        total: 63,
        registered: 52,
        unregistered: 11,
      },
      {
        timeId: "t-16",
        time: "15:00 - 16:00",
        students: 62,
        staff: 5,
        total: 67,
        registered: 56,
        unregistered: 11,
      },
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 42,
        staff: 3,
        total: 45,
        registered: 37,
        unregistered: 8,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 55,
        staff: 4,
        total: 59,
        registered: 50,
        unregistered: 9,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 48,
        staff: 4,
        total: 52,
        registered: 44,
        unregistered: 8,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 35,
        staff: 3,
        total: 38,
        registered: 33,
        unregistered: 5,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 22,
        staff: 2,
        total: 24,
        registered: 21,
        unregistered: 3,
      },
    ],
  },
  {
    facultyId: "f-12",
    faculty: "คณะทันตแพทยศาสตร์",
    data: [
      {
        timeId: "t-9",
        time: "08:00 - 09:00",
        students: 32,
        staff: 3,
        total: 35,
        registered: 28,
        unregistered: 7,
      },
      {
        timeId: "t-10",
        time: "09:00 - 10:00",
        students: 38,
        staff: 3,
        total: 41,
        registered: 33,
        unregistered: 8,
      },
      {
        timeId: "t-11",
        time: "10:00 - 11:00",
        students: 42,
        staff: 4,
        total: 46,
        registered: 37,
        unregistered: 9,
      },
      {
        timeId: "t-12",
        time: "11:00 - 12:00",
        students: 48,
        staff: 4,
        total: 52,
        registered: 42,
        unregistered: 10,
      },
      {
        timeId: "t-13",
        time: "12:00 - 13:00",
        students: 40,
        staff: 3,
        total: 43,
        registered: 36,
        unregistered: 7,
      },
      {
        timeId: "t-14",
        time: "13:00 - 14:00",
        students: 44,
        staff: 4,
        total: 48,
        registered: 39,
        unregistered: 9,
      },
      {
        timeId: "t-15",
        time: "14:00 - 15:00",
        students: 48,
        staff: 4,
        total: 52,
        registered: 43,
        unregistered: 9,
      },
      {
        timeId: "t-16",
        time: "15:00 - 16:00",
        students: 52,
        staff: 4,
        total: 56,
        registered: 47,
        unregistered: 9,
      },
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 32,
        staff: 3,
        total: 35,
        registered: 28,
        unregistered: 7,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 42,
        staff: 4,
        total: 46,
        registered: 38,
        unregistered: 8,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 38,
        staff: 3,
        total: 41,
        registered: 35,
        unregistered: 6,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 28,
        staff: 2,
        total: 30,
        registered: 26,
        unregistered: 4,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 18,
        staff: 2,
        total: 20,
        registered: 17,
        unregistered: 3,
      },
    ],
  },
  {
    facultyId: "f-13",
    faculty: "คณะพยาบาลศาสตร์",
    data: [
      {
        timeId: "t-9",
        time: "08:00 - 09:00",
        students: 45,
        staff: 4,
        total: 49,
        registered: 40,
        unregistered: 9,
      },
      {
        timeId: "t-10",
        time: "09:00 - 10:00",
        students: 50,
        staff: 4,
        total: 54,
        registered: 44,
        unregistered: 10,
      },
      {
        timeId: "t-11",
        time: "10:00 - 11:00",
        students: 55,
        staff: 5,
        total: 60,
        registered: 49,
        unregistered: 11,
      },
      {
        timeId: "t-12",
        time: "11:00 - 12:00",
        students: 62,
        staff: 5,
        total: 67,
        registered: 55,
        unregistered: 12,
      },
      {
        timeId: "t-13",
        time: "12:00 - 13:00",
        students: 52,
        staff: 4,
        total: 56,
        registered: 47,
        unregistered: 9,
      },
      {
        timeId: "t-14",
        time: "13:00 - 14:00",
        students: 58,
        staff: 5,
        total: 63,
        registered: 52,
        unregistered: 11,
      },
      {
        timeId: "t-15",
        time: "14:00 - 15:00",
        students: 62,
        staff: 5,
        total: 67,
        registered: 56,
        unregistered: 11,
      },
      {
        timeId: "t-16",
        time: "15:00 - 16:00",
        students: 68,
        staff: 6,
        total: 74,
        registered: 61,
        unregistered: 13,
      },
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 45,
        staff: 4,
        total: 49,
        registered: 39,
        unregistered: 10,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 58,
        staff: 5,
        total: 63,
        registered: 53,
        unregistered: 10,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 52,
        staff: 4,
        total: 56,
        registered: 48,
        unregistered: 8,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 38,
        staff: 3,
        total: 41,
        registered: 35,
        unregistered: 6,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 25,
        staff: 2,
        total: 27,
        registered: 23,
        unregistered: 4,
      },
    ],
  },
  {
    facultyId: "f-14",
    faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
    data: [
      {
        timeId: "t-9",
        time: "08:00 - 09:00",
        students: 62,
        staff: 5,
        total: 67,
        registered: 55,
        unregistered: 12,
      },
      {
        timeId: "t-10",
        time: "09:00 - 10:00",
        students: 68,
        staff: 6,
        total: 74,
        registered: 60,
        unregistered: 14,
      },
      {
        timeId: "t-11",
        time: "10:00 - 11:00",
        students: 72,
        staff: 6,
        total: 78,
        registered: 64,
        unregistered: 14,
      },
      {
        timeId: "t-12",
        time: "11:00 - 12:00",
        students: 78,
        staff: 7,
        total: 85,
        registered: 70,
        unregistered: 15,
      },
      {
        timeId: "t-13",
        time: "12:00 - 13:00",
        students: 68,
        staff: 6,
        total: 74,
        registered: 61,
        unregistered: 13,
      },
      {
        timeId: "t-14",
        time: "13:00 - 14:00",
        students: 74,
        staff: 6,
        total: 80,
        registered: 66,
        unregistered: 14,
      },
      {
        timeId: "t-15",
        time: "14:00 - 15:00",
        students: 80,
        staff: 7,
        total: 87,
        registered: 71,
        unregistered: 16,
      },
      {
        timeId: "t-16",
        time: "15:00 - 16:00",
        students: 85,
        staff: 7,
        total: 92,
        registered: 76,
        unregistered: 16,
      },
      {
        timeId: "t-17",
        time: "16:00 - 17:00",
        students: 62,
        staff: 5,
        total: 67,
        registered: 54,
        unregistered: 13,
      },
      {
        timeId: "t-18",
        time: "17:00 - 18:00",
        students: 78,
        staff: 7,
        total: 85,
        registered: 72,
        unregistered: 13,
      },
      {
        timeId: "t-19",
        time: "18:00 - 19:00",
        students: 68,
        staff: 6,
        total: 74,
        registered: 63,
        unregistered: 11,
      },
      {
        timeId: "t-20",
        time: "19:00 - 20:00",
        students: 52,
        staff: 4,
        total: 56,
        registered: 48,
        unregistered: 8,
      },
      {
        timeId: "t-21",
        time: "20:00 - 21:00",
        students: 35,
        staff: 3,
        total: 38,
        registered: 33,
        unregistered: 5,
      },
    ],
  },
];

// Deep Insight Time Data with Full Faculty data
export const deepInsightTimeData = [
  {
    timeId: "t-9",
    time: "08:00 - 09:00",
    data: [
      {
        facultyId: "f-1",
        faculty: "คณะวิศวกรรมศาสตร์",
        students: 120,
        staff: 30,
        total: 150,
        registered: 120,
        unregistered: 30,
      },
      {
        facultyId: "f-2",
        faculty: "คณะอักษรศาสตร์",
        students: 80,
        staff: 20,
        total: 100,
        registered: 80,
        unregistered: 20,
      },
      {
        facultyId: "f-3",
        faculty: "คณะวิทยาศาสตร์",
        students: 100,
        staff: 25,
        total: 125,
        registered: 100,
        unregistered: 25,
      },
      {
        facultyId: "f-4",
        faculty: "คณะสถาปัตยกรรมศาสตร์",
        students: 60,
        staff: 15,
        total: 75,
        registered: 60,
        unregistered: 15,
      },
      {
        facultyId: "f-5",
        faculty: "คณะพาณิชยศาสตร์และการบัญชี",
        students: 120,
        staff: 30,
        total: 150,
        registered: 120,
        unregistered: 30,
      },
      {
        facultyId: "f-6",
        faculty: "คณะครุศาสตร์",
        students: 68,
        staff: 7,
        total: 75,
        registered: 62,
        unregistered: 13,
      },
      {
        facultyId: "f-7",
        faculty: "คณะนิเทศศาสตร์",
        students: 92,
        staff: 8,
        total: 100,
        registered: 80,
        unregistered: 20,
      },
      {
        facultyId: "f-8",
        faculty: "คณะเศรษฐศาสตร์",
        students: 115,
        staff: 10,
        total: 125,
        registered: 98,
        unregistered: 27,
      },
      {
        facultyId: "f-9",
        faculty: "คณะนิติศาสตร์",
        students: 88,
        staff: 7,
        total: 95,
        registered: 78,
        unregistered: 17,
      },
      {
        facultyId: "f-10",
        faculty: "คณะสัตวแพทยศาสตร์",
        students: 52,
        staff: 5,
        total: 57,
        registered: 45,
        unregistered: 12,
      },
      {
        facultyId: "f-11",
        faculty: "คณะเภสัชศาสตร์",
        students: 42,
        staff: 3,
        total: 45,
        registered: 37,
        unregistered: 8,
      },
      {
        facultyId: "f-12",
        faculty: "คณะทันตแพทยศาสตร์",
        students: 32,
        staff: 3,
        total: 35,
        registered: 28,
        unregistered: 7,
      },
      {
        facultyId: "f-13",
        faculty: "คณะพยาบาลศาสตร์",
        students: 45,
        staff: 4,
        total: 49,
        registered: 40,
        unregistered: 9,
      },
      {
        facultyId: "f-14",
        faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
        students: 62,
        staff: 5,
        total: 67,
        registered: 55,
        unregistered: 12,
      },
    ],
  },
  {
    timeId: "t-10",
    time: "09:00 - 10:00",
    data: [
      {
        facultyId: "f-1",
        faculty: "คณะวิศวกรรมศาสตร์",
        students: 160,
        staff: 40,
        total: 200,
        registered: 160,
        unregistered: 40,
      },
      {
        facultyId: "f-2",
        faculty: "คณะอักษรศาสตร์",
        students: 100,
        staff: 25,
        total: 125,
        registered: 100,
        unregistered: 25,
      },
      {
        facultyId: "f-3",
        faculty: "คณะวิทยาศาสตร์",
        students: 140,
        staff: 35,
        total: 175,
        registered: 140,
        unregistered: 35,
      },
      {
        facultyId: "f-4",
        faculty: "คณะสถาปัตยกรรมศาสตร์",
        students: 80,
        staff: 20,
        total: 100,
        registered: 80,
        unregistered: 20,
      },
      {
        facultyId: "f-5",
        faculty: "คณะพาณิชยศาสตร์และการบัญชี",
        students: 140,
        staff: 35,
        total: 175,
        registered: 140,
        unregistered: 35,
      },
      {
        facultyId: "f-6",
        faculty: "คณะครุศาสตร์",
        students: 75,
        staff: 8,
        total: 83,
        registered: 68,
        unregistered: 15,
      },
      {
        facultyId: "f-7",
        faculty: "คณะนิเทศศาสตร์",
        students: 95,
        staff: 9,
        total: 104,
        registered: 85,
        unregistered: 19,
      },
      {
        facultyId: "f-8",
        faculty: "คณะเศรษฐศาสตร์",
        students: 120,
        staff: 11,
        total: 131,
        registered: 105,
        unregistered: 26,
      },
      {
        facultyId: "f-9",
        faculty: "คณะนิติศาสตร์",
        students: 95,
        staff: 8,
        total: 103,
        registered: 85,
        unregistered: 18,
      },
      {
        facultyId: "f-10",
        faculty: "คณะสัตวแพทยศาสตร์",
        students: 58,
        staff: 5,
        total: 63,
        registered: 50,
        unregistered: 13,
      },
      {
        facultyId: "f-11",
        faculty: "คณะเภสัชศาสตร์",
        students: 48,
        staff: 4,
        total: 52,
        registered: 42,
        unregistered: 10,
      },
      {
        facultyId: "f-12",
        faculty: "คณะทันตแพทยศาสตร์",
        students: 38,
        staff: 3,
        total: 41,
        registered: 33,
        unregistered: 8,
      },
      {
        facultyId: "f-13",
        faculty: "คณะพยาบาลศาสตร์",
        students: 50,
        staff: 4,
        total: 54,
        registered: 44,
        unregistered: 10,
      },
      {
        facultyId: "f-14",
        faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
        students: 68,
        staff: 6,
        total: 74,
        registered: 60,
        unregistered: 14,
      },
    ],
  },
  {
    timeId: "t-11",
    time: "10:00 - 11:00",
    data: [
      {
        facultyId: "f-1",
        faculty: "คณะวิศวกรรมศาสตร์",
        students: 180,
        staff: 45,
        total: 225,
        registered: 180,
        unregistered: 45,
      },
      {
        facultyId: "f-2",
        faculty: "คณะอักษรศาสตร์",
        students: 140,
        staff: 35,
        total: 175,
        registered: 140,
        unregistered: 35,
      },
      {
        facultyId: "f-3",
        faculty: "คณะวิทยาศาสตร์",
        students: 180,
        staff: 45,
        total: 225,
        registered: 180,
        unregistered: 45,
      },
      {
        facultyId: "f-4",
        faculty: "คณะสถาปัตยกรรมศาสตร์",
        students: 100,
        staff: 25,
        total: 125,
        registered: 100,
        unregistered: 25,
      },
      {
        facultyId: "f-5",
        faculty: "คณะพาณิชยศาสตร์และการบัญชี",
        students: 160,
        staff: 40,
        total: 200,
        registered: 160,
        unregistered: 40,
      },
      {
        facultyId: "f-6",
        faculty: "คณะครุศาสตร์",
        students: 82,
        staff: 9,
        total: 91,
        registered: 75,
        unregistered: 16,
      },
      {
        facultyId: "f-7",
        faculty: "คณะนิเทศศาสตร์",
        students: 105,
        staff: 10,
        total: 115,
        registered: 92,
        unregistered: 23,
      },
      {
        facultyId: "f-8",
        faculty: "คณะเศรษฐศาสตร์",
        students: 130,
        staff: 12,
        total: 142,
        registered: 115,
        unregistered: 27,
      },
      {
        facultyId: "f-9",
        faculty: "คณะนิติศาสตร์",
        students: 102,
        staff: 9,
        total: 111,
        registered: 92,
        unregistered: 19,
      },
      {
        facultyId: "f-10",
        faculty: "คณะสัตวแพทยศาสตร์",
        students: 62,
        staff: 6,
        total: 68,
        registered: 55,
        unregistered: 13,
      },
      {
        facultyId: "f-11",
        faculty: "คณะเภสัชศาสตร์",
        students: 52,
        staff: 4,
        total: 56,
        registered: 46,
        unregistered: 10,
      },
      {
        facultyId: "f-12",
        faculty: "คณะทันตแพทยศาสตร์",
        students: 42,
        staff: 4,
        total: 46,
        registered: 37,
        unregistered: 9,
      },
      {
        facultyId: "f-13",
        faculty: "คณะพยาบาลศาสตร์",
        students: 55,
        staff: 5,
        total: 60,
        registered: 49,
        unregistered: 11,
      },
      {
        facultyId: "f-14",
        faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
        students: 72,
        staff: 6,
        total: 78,
        registered: 64,
        unregistered: 14,
      },
    ],
  },
  {
    timeId: "t-12",
    time: "11:00 - 12:00",
    data: [
      {
        facultyId: "f-1",
        faculty: "คณะวิศวกรรมศาสตร์",
        students: 200,
        staff: 50,
        total: 250,
        registered: 200,
        unregistered: 50,
      },
      {
        facultyId: "f-2",
        faculty: "คณะอักษรศาสตร์",
        students: 200,
        staff: 50,
        total: 250,
        registered: 200,
        unregistered: 50,
      },
      {
        facultyId: "f-3",
        faculty: "คณะวิทยาศาสตร์",
        students: 220,
        staff: 55,
        total: 275,
        registered: 220,
        unregistered: 55,
      },
      {
        facultyId: "f-4",
        faculty: "คณะสถาปัตยกรรมศาสตร์",
        students: 120,
        staff: 30,
        total: 150,
        registered: 120,
        unregistered: 30,
      },
      {
        facultyId: "f-5",
        faculty: "คณะพาณิชยศาสตร์และการบัญชี",
        students: 180,
        staff: 45,
        total: 225,
        registered: 180,
        unregistered: 45,
      },
      {
        facultyId: "f-6",
        faculty: "คณะครุศาสตร์",
        students: 88,
        staff: 9,
        total: 97,
        registered: 80,
        unregistered: 17,
      },
      {
        facultyId: "f-7",
        faculty: "คณะนิเทศศาสตร์",
        students: 112,
        staff: 10,
        total: 122,
        registered: 98,
        unregistered: 24,
      },
      {
        facultyId: "f-8",
        faculty: "คณะเศรษฐศาสตร์",
        students: 138,
        staff: 12,
        total: 150,
        registered: 122,
        unregistered: 28,
      },
      {
        facultyId: "f-9",
        faculty: "คณะนิติศาสตร์",
        students: 108,
        staff: 9,
        total: 117,
        registered: 98,
        unregistered: 19,
      },
      {
        facultyId: "f-10",
        faculty: "คณะสัตวแพทยศาสตร์",
        students: 68,
        staff: 6,
        total: 74,
        registered: 60,
        unregistered: 14,
      },
      {
        facultyId: "f-11",
        faculty: "คณะเภสัชศาสตร์",
        students: 58,
        staff: 5,
        total: 63,
        registered: 52,
        unregistered: 11,
      },
      {
        facultyId: "f-12",
        faculty: "คณะทันตแพทยศาสตร์",
        students: 48,
        staff: 4,
        total: 52,
        registered: 42,
        unregistered: 10,
      },
      {
        facultyId: "f-13",
        faculty: "คณะพยาบาลศาสตร์",
        students: 62,
        staff: 5,
        total: 67,
        registered: 55,
        unregistered: 12,
      },
      {
        facultyId: "f-14",
        faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
        students: 78,
        staff: 7,
        total: 85,
        registered: 70,
        unregistered: 15,
      },
    ],
  },
  {
    timeId: "t-13",
    time: "12:00 - 13:00",
    data: [
      {
        facultyId: "f-1",
        faculty: "คณะวิศวกรรมศาสตร์",
        students: 160,
        staff: 40,
        total: 200,
        registered: 160,
        unregistered: 40,
      },
      {
        facultyId: "f-2",
        faculty: "คณะอักษรศาสตร์",
        students: 180,
        staff: 45,
        total: 225,
        registered: 180,
        unregistered: 45,
      },
      {
        facultyId: "f-3",
        faculty: "คณะวิทยาศาสตร์",
        students: 160,
        staff: 40,
        total: 200,
        registered: 160,
        unregistered: 40,
      },
      {
        facultyId: "f-4",
        faculty: "คณะสถาปัตยกรรมศาสตร์",
        students: 100,
        staff: 25,
        total: 125,
        registered: 100,
        unregistered: 25,
      },
      {
        facultyId: "f-5",
        faculty: "คณะพาณิชยศาสตร์และการบัญชี",
        students: 140,
        staff: 35,
        total: 175,
        registered: 140,
        unregistered: 35,
      },
      {
        facultyId: "f-6",
        faculty: "คณะครุศาสตร์",
        students: 78,
        staff: 8,
        total: 86,
        registered: 72,
        unregistered: 14,
      },
      {
        facultyId: "f-7",
        faculty: "คณะนิเทศศาสตร์",
        students: 98,
        staff: 9,
        total: 107,
        registered: 88,
        unregistered: 19,
      },
      {
        facultyId: "f-8",
        faculty: "คณะเศรษฐศาสตร์",
        students: 122,
        staff: 11,
        total: 133,
        registered: 110,
        unregistered: 23,
      },
      {
        facultyId: "f-9",
        faculty: "คณะนิติศาสตร์",
        students: 95,
        staff: 8,
        total: 103,
        registered: 86,
        unregistered: 17,
      },
      {
        facultyId: "f-10",
        faculty: "คณะสัตวแพทยศาสตร์",
        students: 58,
        staff: 5,
        total: 63,
        registered: 52,
        unregistered: 11,
      },
      {
        facultyId: "f-11",
        faculty: "คณะเภสัชศาสตร์",
        students: 48,
        staff: 4,
        total: 52,
        registered: 43,
        unregistered: 9,
      },
      {
        facultyId: "f-12",
        faculty: "คณะทันตแพทยศาสตร์",
        students: 40,
        staff: 3,
        total: 43,
        registered: 36,
        unregistered: 7,
      },
      {
        facultyId: "f-13",
        faculty: "คณะพยาบาลศาสตร์",
        students: 52,
        staff: 4,
        total: 56,
        registered: 47,
        unregistered: 9,
      },
      {
        facultyId: "f-14",
        faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
        students: 68,
        staff: 6,
        total: 74,
        registered: 61,
        unregistered: 13,
      },
    ],
  },
  {
    timeId: "t-14",
    time: "13:00 - 14:00",
    data: [
      {
        facultyId: "f-1",
        faculty: "คณะวิศวกรรมศาสตร์",
        students: 180,
        staff: 45,
        total: 225,
        registered: 180,
        unregistered: 45,
      },
      {
        facultyId: "f-2",
        faculty: "คณะอักษรศาสตร์",
        students: 240,
        staff: 60,
        total: 300,
        registered: 240,
        unregistered: 60,
      },
      {
        facultyId: "f-3",
        faculty: "คณะวิทยาศาสตร์",
        students: 200,
        staff: 50,
        total: 250,
        registered: 200,
        unregistered: 50,
      },
      {
        facultyId: "f-4",
        faculty: "คณะสถาปัตยกรรมศาสตร์",
        students: 140,
        staff: 35,
        total: 175,
        registered: 140,
        unregistered: 35,
      },
      {
        facultyId: "f-5",
        faculty: "คณะพาณิชยศาสตร์และการบัญชี",
        students: 160,
        staff: 40,
        total: 200,
        registered: 160,
        unregistered: 40,
      },
      {
        facultyId: "f-6",
        faculty: "คณะครุศาสตร์",
        students: 85,
        staff: 8,
        total: 93,
        registered: 78,
        unregistered: 15,
      },
      {
        facultyId: "f-7",
        faculty: "คณะนิเทศศาสตร์",
        students: 108,
        staff: 10,
        total: 118,
        registered: 95,
        unregistered: 23,
      },
      {
        facultyId: "f-8",
        faculty: "คณะเศรษฐศาสตร์",
        students: 132,
        staff: 12,
        total: 144,
        registered: 118,
        unregistered: 26,
      },
      {
        facultyId: "f-9",
        faculty: "คณะนิติศาสตร์",
        students: 102,
        staff: 9,
        total: 111,
        registered: 92,
        unregistered: 19,
      },
      {
        facultyId: "f-10",
        faculty: "คณะสัตวแพทยศาสตร์",
        students: 64,
        staff: 6,
        total: 70,
        registered: 57,
        unregistered: 13,
      },
      {
        facultyId: "f-11",
        faculty: "คณะเภสัชศาสตร์",
        students: 54,
        staff: 4,
        total: 58,
        registered: 48,
        unregistered: 10,
      },
      {
        facultyId: "f-12",
        faculty: "คณะทันตแพทยศาสตร์",
        students: 44,
        staff: 4,
        total: 48,
        registered: 39,
        unregistered: 9,
      },
      {
        facultyId: "f-13",
        faculty: "คณะพยาบาลศาสตร์",
        students: 58,
        staff: 5,
        total: 63,
        registered: 52,
        unregistered: 11,
      },
      {
        facultyId: "f-14",
        faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
        students: 74,
        staff: 6,
        total: 80,
        registered: 66,
        unregistered: 14,
      },
    ],
  },
  {
    timeId: "t-15",
    time: "14:00 - 15:00",
    data: [
      {
        facultyId: "f-1",
        faculty: "คณะวิศวกรรมศาสตร์",
        students: 220,
        staff: 55,
        total: 275,
        registered: 220,
        unregistered: 55,
      },
      {
        facultyId: "f-2",
        faculty: "คณะอักษรศาสตร์",
        students: 320,
        staff: 80,
        total: 400,
        registered: 320,
        unregistered: 80,
      },
      {
        facultyId: "f-3",
        faculty: "คณะวิทยาศาสตร์",
        students: 240,
        staff: 60,
        total: 300,
        registered: 240,
        unregistered: 60,
      },
      {
        facultyId: "f-4",
        faculty: "คณะสถาปัตยกรรมศาสตร์",
        students: 180,
        staff: 45,
        total: 225,
        registered: 180,
        unregistered: 45,
      },
      {
        facultyId: "f-5",
        faculty: "คณะพาณิชยศาสตร์และการบัญชี",
        students: 200,
        staff: 50,
        total: 250,
        registered: 200,
        unregistered: 50,
      },
      {
        facultyId: "f-6",
        faculty: "คณะครุศาสตร์",
        students: 92,
        staff: 9,
        total: 101,
        registered: 84,
        unregistered: 17,
      },
      {
        facultyId: "f-7",
        faculty: "คณะนิเทศศาสตร์",
        students: 115,
        staff: 10,
        total: 125,
        registered: 102,
        unregistered: 23,
      },
      {
        facultyId: "f-8",
        faculty: "คณะเศรษฐศาสตร์",
        students: 140,
        staff: 12,
        total: 152,
        registered: 125,
        unregistered: 27,
      },
      {
        facultyId: "f-9",
        faculty: "คณะนิติศาสตร์",
        students: 108,
        staff: 9,
        total: 117,
        registered: 98,
        unregistered: 19,
      },
      {
        facultyId: "f-10",
        faculty: "คณะสัตวแพทยศาสตร์",
        students: 70,
        staff: 6,
        total: 76,
        registered: 62,
        unregistered: 14,
      },
      {
        facultyId: "f-11",
        faculty: "คณะเภสัชศาสตร์",
        students: 58,
        staff: 5,
        total: 63,
        registered: 52,
        unregistered: 11,
      },
      {
        facultyId: "f-12",
        faculty: "คณะทันตแพทยศาสตร์",
        students: 48,
        staff: 4,
        total: 52,
        registered: 43,
        unregistered: 9,
      },
      {
        facultyId: "f-13",
        faculty: "คณะพยาบาลศาสตร์",
        students: 62,
        staff: 5,
        total: 67,
        registered: 56,
        unregistered: 11,
      },
      {
        facultyId: "f-14",
        faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
        students: 80,
        staff: 7,
        total: 87,
        registered: 71,
        unregistered: 16,
      },
    ],
  },
  {
    timeId: "t-16",
    time: "15:00 - 16:00",
    data: [
      {
        facultyId: "f-1",
        faculty: "คณะวิศวกรรมศาสตร์",
        students: 240,
        staff: 60,
        total: 300,
        registered: 240,
        unregistered: 60,
      },
      {
        facultyId: "f-2",
        faculty: "คณะอักษรศาสตร์",
        students: 360,
        staff: 90,
        total: 450,
        registered: 360,
        unregistered: 90,
      },
      {
        facultyId: "f-3",
        faculty: "คณะวิทยาศาสตร์",
        students: 280,
        staff: 70,
        total: 350,
        registered: 280,
        unregistered: 70,
      },
      {
        facultyId: "f-4",
        faculty: "คณะสถาปัตยกรรมศาสตร์",
        students: 220,
        staff: 55,
        total: 275,
        registered: 220,
        unregistered: 55,
      },
      {
        facultyId: "f-5",
        faculty: "คณะพาณิชยศาสตร์และการบัญชี",
        students: 240,
        staff: 60,
        total: 300,
        registered: 240,
        unregistered: 60,
      },
      {
        facultyId: "f-6",
        faculty: "คณะครุศาสตร์",
        students: 98,
        staff: 10,
        total: 108,
        registered: 90,
        unregistered: 18,
      },
      {
        facultyId: "f-7",
        faculty: "คณะนิเทศศาสตร์",
        students: 122,
        staff: 11,
        total: 133,
        registered: 108,
        unregistered: 25,
      },
      {
        facultyId: "f-8",
        faculty: "คณะเศรษฐศาสตร์",
        students: 148,
        staff: 13,
        total: 161,
        registered: 132,
        unregistered: 29,
      },
      {
        facultyId: "f-9",
        faculty: "คณะนิติศาสตร์",
        students: 115,
        staff: 10,
        total: 125,
        registered: 104,
        unregistered: 21,
      },
      {
        facultyId: "f-10",
        faculty: "คณะสัตวแพทยศาสตร์",
        students: 75,
        staff: 7,
        total: 82,
        registered: 67,
        unregistered: 15,
      },
      {
        facultyId: "f-11",
        faculty: "คณะเภสัชศาสตร์",
        students: 62,
        staff: 5,
        total: 67,
        registered: 56,
        unregistered: 11,
      },
      {
        facultyId: "f-12",
        faculty: "คณะทันตแพทยศาสตร์",
        students: 52,
        staff: 4,
        total: 56,
        registered: 47,
        unregistered: 9,
      },
      {
        facultyId: "f-13",
        faculty: "คณะพยาบาลศาสตร์",
        students: 68,
        staff: 6,
        total: 74,
        registered: 61,
        unregistered: 13,
      },
      {
        facultyId: "f-14",
        faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
        students: 85,
        staff: 7,
        total: 92,
        registered: 76,
        unregistered: 16,
      },
    ],
  },
  {
    timeId: "t-17",
    time: "16:00 - 17:00",
    data: [
      {
        facultyId: "f-1",
        faculty: "คณะวิศวกรรมศาสตร์",
        students: 280,
        staff: 70,
        total: 350,
        registered: 280,
        unregistered: 70,
      },
      {
        facultyId: "f-2",
        faculty: "คณะอักษรศาสตร์",
        students: 120,
        staff: 30,
        total: 150,
        registered: 120,
        unregistered: 30,
      },
      {
        facultyId: "f-3",
        faculty: "คณะวิทยาศาสตร์",
        students: 160,
        staff: 40,
        total: 200,
        registered: 160,
        unregistered: 40,
      },
      {
        facultyId: "f-4",
        faculty: "คณะสถาปัตยกรรมศาสตร์",
        students: 40,
        staff: 10,
        total: 50,
        registered: 40,
        unregistered: 10,
      },
      {
        facultyId: "f-5",
        faculty: "คณะพาณิชยศาสตร์และการบัญชี",
        students: 180,
        staff: 45,
        total: 225,
        registered: 180,
        unregistered: 45,
      },
      {
        facultyId: "f-6",
        faculty: "คณะครุศาสตร์",
        students: 68,
        staff: 7,
        total: 75,
        registered: 62,
        unregistered: 13,
      },
      {
        facultyId: "f-7",
        faculty: "คณะนิเทศศาสตร์",
        students: 92,
        staff: 8,
        total: 100,
        registered: 80,
        unregistered: 20,
      },
      {
        facultyId: "f-8",
        faculty: "คณะเศรษฐศาสตร์",
        students: 115,
        staff: 10,
        total: 125,
        registered: 98,
        unregistered: 27,
      },
      {
        facultyId: "f-9",
        faculty: "คณะนิติศาสตร์",
        students: 88,
        staff: 7,
        total: 95,
        registered: 78,
        unregistered: 17,
      },
      {
        facultyId: "f-10",
        faculty: "คณะสัตวแพทยศาสตร์",
        students: 52,
        staff: 5,
        total: 57,
        registered: 45,
        unregistered: 12,
      },
      {
        facultyId: "f-11",
        faculty: "คณะเภสัชศาสตร์",
        students: 42,
        staff: 3,
        total: 45,
        registered: 37,
        unregistered: 8,
      },
      {
        facultyId: "f-12",
        faculty: "คณะทันตแพทยศาสตร์",
        students: 32,
        staff: 3,
        total: 35,
        registered: 28,
        unregistered: 7,
      },
      {
        facultyId: "f-13",
        faculty: "คณะพยาบาลศาสตร์",
        students: 45,
        staff: 4,
        total: 49,
        registered: 39,
        unregistered: 10,
      },
      {
        facultyId: "f-14",
        faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
        students: 62,
        staff: 5,
        total: 67,
        registered: 54,
        unregistered: 13,
      },
    ],
  },
  {
    timeId: "t-18",
    time: "17:00 - 18:00",
    data: [
      {
        facultyId: "f-1",
        faculty: "คณะวิศวกรรมศาสตร์",
        students: 340,
        staff: 85,
        total: 425,
        registered: 340,
        unregistered: 85,
      },
      {
        facultyId: "f-2",
        faculty: "คณะอักษรศาสตร์",
        students: 480,
        staff: 120,
        total: 600,
        registered: 480,
        unregistered: 120,
      },
      {
        facultyId: "f-3",
        faculty: "คณะวิทยาศาสตร์",
        students: 240,
        staff: 60,
        total: 300,
        registered: 240,
        unregistered: 60,
      },
      {
        facultyId: "f-4",
        faculty: "คณะสถาปัตยกรรมศาสตร์",
        students: 120,
        staff: 30,
        total: 150,
        registered: 120,
        unregistered: 30,
      },
      {
        facultyId: "f-5",
        faculty: "คณะพาณิชยศาสตร์และการบัญชี",
        students: 220,
        staff: 55,
        total: 275,
        registered: 220,
        unregistered: 55,
      },
      {
        facultyId: "f-6",
        faculty: "คณะครุศาสตร์",
        students: 95,
        staff: 8,
        total: 103,
        registered: 88,
        unregistered: 15,
      },
      {
        facultyId: "f-7",
        faculty: "คณะนิเทศศาสตร์",
        students: 118,
        staff: 10,
        total: 128,
        registered: 110,
        unregistered: 18,
      },
      {
        facultyId: "f-8",
        faculty: "คณะเศรษฐศาสตร์",
        students: 142,
        staff: 12,
        total: 154,
        registered: 130,
        unregistered: 24,
      },
      {
        facultyId: "f-9",
        faculty: "คณะนิติศาสตร์",
        students: 112,
        staff: 10,
        total: 122,
        registered: 105,
        unregistered: 17,
      },
      {
        facultyId: "f-10",
        faculty: "คณะสัตวแพทยศาสตร์",
        students: 68,
        staff: 6,
        total: 74,
        registered: 62,
        unregistered: 12,
      },
      {
        facultyId: "f-11",
        faculty: "คณะเภสัชศาสตร์",
        students: 55,
        staff: 4,
        total: 59,
        registered: 50,
        unregistered: 9,
      },
      {
        facultyId: "f-12",
        faculty: "คณะทันตแพทยศาสตร์",
        students: 42,
        staff: 4,
        total: 46,
        registered: 38,
        unregistered: 8,
      },
      {
        facultyId: "f-13",
        faculty: "คณะพยาบาลศาสตร์",
        students: 58,
        staff: 5,
        total: 63,
        registered: 53,
        unregistered: 10,
      },
      {
        facultyId: "f-14",
        faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
        students: 78,
        staff: 7,
        total: 85,
        registered: 72,
        unregistered: 13,
      },
    ],
  },
  {
    timeId: "t-19",
    time: "18:00 - 19:00",
    data: [
      {
        facultyId: "f-1",
        faculty: "คณะวิศวกรรมศาสตร์",
        students: 240,
        staff: 60,
        total: 300,
        registered: 240,
        unregistered: 60,
      },
      {
        facultyId: "f-2",
        faculty: "คณะอักษรศาสตร์",
        students: 400,
        staff: 100,
        total: 500,
        registered: 400,
        unregistered: 100,
      },
      {
        facultyId: "f-3",
        faculty: "คณะวิทยาศาสตร์",
        students: 320,
        staff: 80,
        total: 400,
        registered: 320,
        unregistered: 80,
      },
      {
        facultyId: "f-4",
        faculty: "คณะสถาปัตยกรรมศาสตร์",
        students: 200,
        staff: 50,
        total: 250,
        registered: 200,
        unregistered: 50,
      },
      {
        facultyId: "f-5",
        faculty: "คณะพาณิชยศาสตร์และการบัญชี",
        students: 260,
        staff: 65,
        total: 325,
        registered: 260,
        unregistered: 65,
      },
      {
        facultyId: "f-6",
        faculty: "คณะครุศาสตร์",
        students: 82,
        staff: 6,
        total: 88,
        registered: 75,
        unregistered: 13,
      },
      {
        facultyId: "f-7",
        faculty: "คณะนิเทศศาสตร์",
        students: 105,
        staff: 9,
        total: 114,
        registered: 98,
        unregistered: 16,
      },
      {
        facultyId: "f-8",
        faculty: "คณะเศรษฐศาสตร์",
        students: 125,
        staff: 10,
        total: 135,
        registered: 115,
        unregistered: 20,
      },
      {
        facultyId: "f-9",
        faculty: "คณะนิติศาสตร์",
        students: 98,
        staff: 8,
        total: 106,
        registered: 92,
        unregistered: 14,
      },
      {
        facultyId: "f-10",
        faculty: "คณะสัตวแพทยศาสตร์",
        students: 58,
        staff: 5,
        total: 63,
        registered: 54,
        unregistered: 9,
      },
      {
        facultyId: "f-11",
        faculty: "คณะเภสัชศาสตร์",
        students: 48,
        staff: 4,
        total: 52,
        registered: 44,
        unregistered: 8,
      },
      {
        facultyId: "f-12",
        faculty: "คณะทันตแพทยศาสตร์",
        students: 38,
        staff: 3,
        total: 41,
        registered: 35,
        unregistered: 6,
      },
      {
        facultyId: "f-13",
        faculty: "คณะพยาบาลศาสตร์",
        students: 52,
        staff: 4,
        total: 56,
        registered: 48,
        unregistered: 8,
      },
      {
        facultyId: "f-14",
        faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
        students: 68,
        staff: 6,
        total: 74,
        registered: 63,
        unregistered: 11,
      },
    ],
  },
  {
    timeId: "t-20",
    time: "19:00 - 20:00",
    data: [
      {
        facultyId: "f-1",
        faculty: "คณะวิศวกรรมศาสตร์",
        students: 160,
        staff: 40,
        total: 200,
        registered: 160,
        unregistered: 40,
      },
      {
        facultyId: "f-2",
        faculty: "คณะอักษรศาสตร์",
        students: 200,
        staff: 50,
        total: 250,
        registered: 200,
        unregistered: 50,
      },
      {
        facultyId: "f-3",
        faculty: "คณะวิทยาศาสตร์",
        students: 280,
        staff: 70,
        total: 350,
        registered: 280,
        unregistered: 70,
      },
      {
        facultyId: "f-4",
        faculty: "คณะสถาปัตยกรรมศาสตร์",
        students: 280,
        staff: 70,
        total: 350,
        registered: 280,
        unregistered: 70,
      },
      {
        facultyId: "f-5",
        faculty: "คณะพาณิชยศาสตร์และการบัญชี",
        students: 240,
        staff: 60,
        total: 300,
        registered: 240,
        unregistered: 60,
      },
      {
        facultyId: "f-6",
        faculty: "คณะครุศาสตร์",
        students: 58,
        staff: 4,
        total: 62,
        registered: 54,
        unregistered: 8,
      },
      {
        facultyId: "f-7",
        faculty: "คณะนิเทศศาสตร์",
        students: 78,
        staff: 6,
        total: 84,
        registered: 72,
        unregistered: 12,
      },
      {
        facultyId: "f-8",
        faculty: "คณะเศรษฐศาสตร์",
        students: 98,
        staff: 8,
        total: 106,
        registered: 92,
        unregistered: 14,
      },
      {
        facultyId: "f-9",
        faculty: "คณะนิติศาสตร์",
        students: 72,
        staff: 6,
        total: 78,
        registered: 68,
        unregistered: 10,
      },
      {
        facultyId: "f-10",
        faculty: "คณะสัตวแพทยศาสตร์",
        students: 42,
        staff: 4,
        total: 46,
        registered: 38,
        unregistered: 8,
      },
      {
        facultyId: "f-11",
        faculty: "คณะเภสัชศาสตร์",
        students: 35,
        staff: 3,
        total: 38,
        registered: 33,
        unregistered: 5,
      },
      {
        facultyId: "f-12",
        faculty: "คณะทันตแพทยศาสตร์",
        students: 28,
        staff: 2,
        total: 30,
        registered: 26,
        unregistered: 4,
      },
      {
        facultyId: "f-13",
        faculty: "คณะพยาบาลศาสตร์",
        students: 38,
        staff: 3,
        total: 41,
        registered: 35,
        unregistered: 6,
      },
      {
        facultyId: "f-14",
        faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
        students: 52,
        staff: 4,
        total: 56,
        registered: 48,
        unregistered: 8,
      },
    ],
  },
  {
    timeId: "t-21",
    time: "20:00 - 21:00",
    data: [
      {
        facultyId: "f-1",
        faculty: "คณะวิศวกรรมศาสตร์",
        students: 80,
        staff: 20,
        total: 100,
        registered: 80,
        unregistered: 20,
      },
      {
        facultyId: "f-2",
        faculty: "คณะอักษรศาสตร์",
        students: 100,
        staff: 25,
        total: 125,
        registered: 100,
        unregistered: 25,
      },
      {
        facultyId: "f-3",
        faculty: "คณะวิทยาศาสตร์",
        students: 200,
        staff: 50,
        total: 250,
        registered: 200,
        unregistered: 50,
      },
      {
        facultyId: "f-4",
        faculty: "คณะสถาปัตยกรรมศาสตร์",
        students: 240,
        staff: 60,
        total: 300,
        registered: 240,
        unregistered: 60,
      },
      {
        facultyId: "f-5",
        faculty: "คณะพาณิชยศาสตร์และการบัญชี",
        students: 200,
        staff: 50,
        total: 250,
        registered: 200,
        unregistered: 50,
      },
      {
        facultyId: "f-6",
        faculty: "คณะครุศาสตร์",
        students: 42,
        staff: 3,
        total: 45,
        registered: 39,
        unregistered: 6,
      },
      {
        facultyId: "f-7",
        faculty: "คณะนิเทศศาสตร์",
        students: 52,
        staff: 4,
        total: 56,
        registered: 48,
        unregistered: 8,
      },
      {
        facultyId: "f-8",
        faculty: "คณะเศรษฐศาสตร์",
        students: 68,
        staff: 6,
        total: 74,
        registered: 65,
        unregistered: 9,
      },
      {
        facultyId: "f-9",
        faculty: "คณะนิติศาสตร์",
        students: 55,
        staff: 4,
        total: 59,
        registered: 52,
        unregistered: 7,
      },
      {
        facultyId: "f-10",
        faculty: "คณะสัตวแพทยศาสตร์",
        students: 28,
        staff: 2,
        total: 30,
        registered: 26,
        unregistered: 4,
      },
      {
        facultyId: "f-11",
        faculty: "คณะเภสัชศาสตร์",
        students: 22,
        staff: 2,
        total: 24,
        registered: 21,
        unregistered: 3,
      },
      {
        facultyId: "f-12",
        faculty: "คณะทันตแพทยศาสตร์",
        students: 18,
        staff: 2,
        total: 20,
        registered: 17,
        unregistered: 3,
      },
      {
        facultyId: "f-13",
        faculty: "คณะพยาบาลศาสตร์",
        students: 25,
        staff: 2,
        total: 27,
        registered: 23,
        unregistered: 4,
      },
      {
        facultyId: "f-14",
        faculty: "คณะวิทยาการเรียนรู้และศึกษาศาสตร์",
        students: 35,
        staff: 3,
        total: 38,
        registered: 33,
        unregistered: 5,
      },
    ],
  },
];
